name: "🚀 문제 추가"
description: "본인이 풀 예정인 문제를 추가합니다"
labels: ["deploy"]
body:
  - type: textarea
    attributes:
      label: 🔗 문제 링크
      placeholder: ⭐️ 제목 : [플랫폼] 문제_이름 / 난이도
     ☑ [BOJ] : 백준
     ☑ [PGS] : 프로그래머스
     ☑ [CFS] : 코드포스
     ☑ [LCE] : 리트코드
     ☑ [ETC] : 그 외 사이트
ex) [BOJ] 트리의 순회 / Gold 2

⭐️ 라벨 : 알고리즘 분류
ex) 트리, 분할 정복, 재귀

<!-- name: Add a problem
about: "본인이 풀 예정인 문제를 추가합니다"
title: "[플랫폼] 문제_이름 / 난이도"
labels: ''
assignees: ''
